import cn from 'classnames'

import { Paper } from '../../../components/ui-components/Paper/index';
import { BluePaper } from '../../../components/ui-components/BluePaper';
import { Button } from '../../../components/ui-components/Button/index';
import { ReactComponent as DownloadIcon } from '../../../images/icons/downloadIcon.svg';
import { ReactComponent as SignIcon } from '../../../images/icons/signIcon.svg';
import { AiOutlineExclamationCircle } from 'react-icons/ai';
import { ServiceAgreementCard } from '../../../components/ui-components/ServiceAgreementCard';

const ServiceAgreement = () => {

    return (
        <>
            <div className="text-green text-2xl font-black mb-8 w-2/3">
                Wildcat Service Agreement
            </div>

            <ServiceAgreementCard title='Wildcat Service Agreement' description='You agreed to the Wildcat Service Agreement on 12-Sept-2023' />

            <BluePaper className='mb-8'>
                <AiOutlineExclamationCircle height={24} />
                <span className='text-xs text-center'>
                    Before you can start lending you’ll need to read and agree (via ETH<br /> wallet signature) to the Wildcat Service Agreement</span>
            </BluePaper>

            <Paper className="max-h-3xl flex flex-col">
                <div className="overflow-scroll mt-5 mb-20 pr-14 pl-8 flex-grow-1">
                    <div className=''>
                        <p className=" font-bold text-xs mb-4">
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur nec fringilla dolor. Vestibulum blandit luctus nisi a aliquet. Nulla fermentum arcu et nisl vulputate viverra. Proin viverra sit amet sapien faucibus maximus. Integer vel urna tempus, elementum erat nec, molestie mi. Vivamus ligula massa, lobortis ac enim sit amet, facilisis ultrices mauris. Mauris rutrum risus a sapien convallis, vitae lacinia est tempus. Donec elit leo, tincidunt id pellentesque vitae, tincidunt vel diam. Donec rhoncus scelerisque tellus sed tempor. Fusce a elit sed tellus venenatis vulputate. Aliquam sit amet lectus at lacus cursus pharetra. Aenean lacinia nisi velit. Nullam pretium odio vitae sapien efficitur auctor.
                            Maecenas suscipit urna id tellus efficitur pretium. Quisque eu ante arcu. Sed non leo et erat tempor pretium ut quis quam. Integer rhoncus dignissim nulla rhoncus dapibus. Sed viverra pretium congue. Donec tincidunt fermentum orci fringilla finibus. Aenean vitae arcu vel lacus tempus pulvinar ut vitae nunc. Suspendisse vel consectetur massa, non ullamcorper orci. Maecenas id dignissim justo. Sed ac euismod purus, id aliquet magna. Pellentesque porttitor erat commodo, imperdiet est ac, luctus orci. Sed eleifend augue non neque interdum ornare.
                            Aenean non porta enim, ut semper est. Aenean eleifend urna eu euismod efficitur. Morbi nec nibh non nisl mollis consectetur. Etiam et semper ex, quis congue magna. Nam venenatis risus ac tempus molestie. Ut ut ultrices ligula, sed iaculis ex. Vivamus viverra semper suscipit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis pretium rutrum pellentesque. Duis rhoncus mollis lacinia.
                            Mauris bibendum libero et dictum porta. Vivamus vulputate elit odio, tincidunt ultrices libero posuere ullamcorper. Curabitur orci est, malesuada at dignissim sed, aliquam eget ante. Praesent vitae est a augue molestie auctor ut eget enim. Sed iaculis aliquam diam ut venenatis. Nunc cursus, nunc ut facilisis vulputate, lectus tortor consequat nisl, viverra mattis neque sapien eget est. Nullam facilisis rhoncus quam, sed malesuada velit aliquam quis. Morbi et nibh eget tortor aliquet laoreet. Ut porta nulla at commodo facilisis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam dapibus purus sed ipsum egestas convallis. Sed et consequat quam. Praesent vel justo nec nisi imperdiet feugiat. Donec sapien ligula, euismod vel ultrices eget, condimentum eu risus.
                            Sed ultricies eleifend risus, quis aliquet velit sagittis eu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut interdum, sapien non dictum molestie, sem nunc porttitor ante, nec pellentesque dolor ex in massa. Donec iaculis in libero at pulvinar. Pellentesque porta libero vel orci malesuada volutpat. Sed dignissim eleifend odio, eget posuere libero suscipit id. Duis consequat ligula sit amet porttitor venenatis. Nam dapibus, libero quis posuere sodales, nulla nisi ultricies neque, et congue ligula quam sed nibh. Ut ligula mauris, pulvinar a sem sit amet, ullamcorper auctor urna. Quisque sollicitudin purus et ipsum tincidunt tempus viverra maximus est. Aliquam gravida, augue sed posuere accumsan, erat urna facilisis tortor, vitae accumsan metus purus vitae risus. Integer at lacinia orci, sed semper sapien. Donec in dui tristique, sagittis augue sit amet, faucibus augue.
                            Nunc feugiat dolor dapibus, facilisis sem vitae, viverra est. Nunc fringilla mi ut odio aliquet, quis condimentum diam interdum. Nulla eget lectus interdum, malesuada libero id, ultrices risus. Proin lacinia interdum pretium. Donec condimentum arcu sed augue commodo, a vestibulum magna commodo. Nullam neque eros, interdum et diam quis, lacinia tempus libero. Fusce aliquet pretium efficitur. Phasellus id egestas sem. Sed sagittis sapien nec condimentum vulputate. Donec posuere gravida metus. Nunc enim enim, malesuada non viverra sit amet, suscipit sed urna. Sed dapibus enim non scelerisque consequat. Suspendisse euismod ornare metus non laoreet. Vivamus vel dui at orci fringilla posuere convallis vitae lorem. Phasellus vel lacinia odio. Nulla convallis pretium mi non aliquet.</p>
                        <p className="font-bold text-xs mb-4">
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur nec fringilla dolor. Vestibulum blandit luctus nisi a aliquet. Nulla fermentum arcu et nisl vulputate viverra. Proin viverra sit amet sapien faucibus maximus. Integer vel urna tempus, elementum erat nec, molestie mi. Vivamus ligula massa, lobortis ac enim sit amet, facilisis ultrices mauris. Mauris rutrum risus a sapien convallis, vitae lacinia est tempus. Donec elit leo, tincidunt id pellentesque vitae, tincidunt vel diam. Donec rhoncus scelerisque tellus sed tempor. Fusce a elit sed tellus venenatis vulputate. Aliquam sit amet lectus at lacus cursus pharetra. Aenean lacinia nisi velit. Nullam pretium odio vitae sapien efficitur auctor.
                            Maecenas suscipit urna id tellus efficitur pretium. Quisque eu ante arcu. Sed non leo et erat tempor pretium ut quis quam. Integer rhoncus dignissim nulla rhoncus dapibus. Sed viverra pretium congue. Donec tincidunt fermentum orci fringilla finibus. Aenean vitae arcu vel lacus tempus pulvinar ut vitae nunc. Suspendisse vel consectetur massa, non ullamcorper orci. Maecenas id dignissim justo. Sed ac euismod purus, id aliquet magna. Pellentesque porttitor erat commodo, imperdiet est ac, luctus orci. Sed eleifend augue non neque interdum ornare.
                            Aenean non porta enim, ut semper est. Aenean eleifend urna eu euismod efficitur. Morbi nec nibh non nisl mollis consectetur. Etiam et semper ex, quis congue magna. Nam venenatis risus ac tempus molestie. Ut ut ultrices ligula, sed iaculis ex. Vivamus viverra semper suscipit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis pretium rutrum pellentesque. Duis rhoncus mollis lacinia.
                            Mauris bibendum libero et dictum porta. Vivamus vulputate elit odio, tincidunt ultrices libero posuere ullamcorper. Curabitur orci est, malesuada at dignissim sed, aliquam eget ante. Praesent vitae est a augue molestie auctor ut eget enim. Sed iaculis aliquam diam ut venenatis. Nunc cursus, nunc ut facilisis vulputate, lectus tortor consequat nisl, viverra mattis neque sapien eget est. Nullam facilisis rhoncus quam, sed malesuada velit aliquam quis. Morbi et nibh eget tortor aliquet laoreet. Ut porta nulla at commodo facilisis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam dapibus purus sed ipsum egestas convallis. Sed et consequat quam. Praesent vel justo nec nisi imperdiet feugiat. Donec sapien ligula, euismod vel ultrices eget, condimentum eu risus.
                            Sed ultricies eleifend risus, quis aliquet velit sagittis eu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut interdum, sapien non dictum molestie, sem nunc porttitor ante, nec pellentesque dolor ex in massa. Donec iaculis in libero at pulvinar. Pellentesque porta libero vel orci malesuada volutpat. Sed dignissim eleifend odio, eget posuere libero suscipit id. Duis consequat ligula sit amet porttitor venenatis. Nam dapibus, libero quis posuere sodales, nulla nisi ultricies neque, et congue ligula quam sed nibh. Ut ligula mauris, pulvinar a sem sit amet, ullamcorper auctor urna. Quisque sollicitudin purus et ipsum tincidunt tempus viverra maximus est. Aliquam gravida, augue sed posuere accumsan, erat urna facilisis tortor, vitae accumsan metus purus vitae risus. Integer at lacinia orci, sed semper sapien. Donec in dui tristique, sagittis augue sit amet, faucibus augue.
                            Nunc feugiat dolor dapibus, facilisis sem vitae, viverra est. Nunc fringilla mi ut odio aliquet, quis condimentum diam interdum. Nulla eget lectus interdum, malesuada libero id, ultrices risus. Proin lacinia interdum pretium. Donec condimentum arcu sed augue commodo, a vestibulum magna commodo. Nullam neque eros, interdum et diam quis, lacinia tempus libero. Fusce aliquet pretium efficitur. Phasellus id egestas sem. Sed sagittis sapien nec condimentum vulputate. Donec posuere gravida metus. Nunc enim enim, malesuada non viverra sit amet, suscipit sed urna. Sed dapibus enim non scelerisque consequat. Suspendisse euismod ornare metus non laoreet. Vivamus vel dui at orci fringilla posuere convallis vitae lorem. Phasellus vel lacinia odio. Nulla convallis pretium mi non aliquet.</p>
                        <p className="font-bold text-xs mb-4">
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur nec fringilla dolor. Vestibulum blandit luctus nisi a aliquet. Nulla fermentum arcu et nisl vulputate viverra. Proin viverra sit amet sapien faucibus maximus. Integer vel urna tempus, elementum erat nec, molestie mi. Vivamus ligula massa, lobortis ac enim sit amet, facilisis ultrices mauris. Mauris rutrum risus a sapien convallis, vitae lacinia est tempus. Donec elit leo, tincidunt id pellentesque vitae, tincidunt vel diam. Donec rhoncus scelerisque tellus sed tempor. Fusce a elit sed tellus venenatis vulputate. Aliquam sit amet lectus at lacus cursus pharetra. Aenean lacinia nisi velit. Nullam pretium odio vitae sapien efficitur auctor.
                            Maecenas suscipit urna id tellus efficitur pretium. Quisque eu ante arcu. Sed non leo et erat tempor pretium ut quis quam. Integer rhoncus dignissim nulla rhoncus dapibus. Sed viverra pretium congue. Donec tincidunt fermentum orci fringilla finibus. Aenean vitae arcu vel lacus tempus pulvinar ut vitae nunc. Suspendisse vel consectetur massa, non ullamcorper orci. Maecenas id dignissim justo. Sed ac euismod purus, id aliquet magna. Pellentesque porttitor erat commodo, imperdiet est ac, luctus orci. Sed eleifend augue non neque interdum ornare.
                            Aenean non porta enim, ut semper est. Aenean eleifend urna eu euismod efficitur. Morbi nec nibh non nisl mollis consectetur. Etiam et semper ex, quis congue magna. Nam venenatis risus ac tempus molestie. Ut ut ultrices ligula, sed iaculis ex. Vivamus viverra semper suscipit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis pretium rutrum pellentesque. Duis rhoncus mollis lacinia.
                            Mauris bibendum libero et dictum porta. Vivamus vulputate elit odio, tincidunt ultrices libero posuere ullamcorper. Curabitur orci est, malesuada at dignissim sed, aliquam eget ante. Praesent vitae est a augue molestie auctor ut eget enim. Sed iaculis aliquam diam ut venenatis. Nunc cursus, nunc ut facilisis vulputate, lectus tortor consequat nisl, viverra mattis neque sapien eget est. Nullam facilisis rhoncus quam, sed malesuada velit aliquam quis. Morbi et nibh eget tortor aliquet laoreet. Ut porta nulla at commodo facilisis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam dapibus purus sed ipsum egestas convallis. Sed et consequat quam. Praesent vel justo nec nisi imperdiet feugiat. Donec sapien ligula, euismod vel ultrices eget, condimentum eu risus.
                            Sed ultricies eleifend risus, quis aliquet velit sagittis eu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut interdum, sapien non dictum molestie, sem nunc porttitor ante, nec pellentesque dolor ex in massa. Donec iaculis in libero at pulvinar. Pellentesque porta libero vel orci malesuada volutpat. Sed dignissim eleifend odio, eget posuere libero suscipit id. Duis consequat ligula sit amet porttitor venenatis. Nam dapibus, libero quis posuere sodales, nulla nisi ultricies neque, et congue ligula quam sed nibh. Ut ligula mauris, pulvinar a sem sit amet, ullamcorper auctor urna. Quisque sollicitudin purus et ipsum tincidunt tempus viverra maximus est. Aliquam gravida, augue sed posuere accumsan, erat urna facilisis tortor, vitae accumsan metus purus vitae risus. Integer at lacinia orci, sed semper sapien. Donec in dui tristique, sagittis augue sit amet, faucibus augue.
                            Nunc feugiat dolor dapibus, facilisis sem vitae, viverra est. Nunc fringilla mi ut odio aliquet, quis condimentum diam interdum. Nulla eget lectus interdum, malesuada libero id, ultrices risus. Proin lacinia interdum pretium. Donec condimentum arcu sed augue commodo, a vestibulum magna commodo. Nullam neque eros, interdum et diam quis, lacinia tempus libero. Fusce aliquet pretium efficitur. Phasellus id egestas sem. Sed sagittis sapien nec condimentum vulputate. Donec posuere gravida metus. Nunc enim enim, malesuada non viverra sit amet, suscipit sed urna. Sed dapibus enim non scelerisque consequat. Suspendisse euismod ornare metus non laoreet. Vivamus vel dui at orci fringilla posuere convallis vitae lorem. Phasellus vel lacinia odio. Nulla convallis pretium mi non aliquet.</p>
                        <p className="font-bold text-xs mb-4">
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur nec fringilla dolor. Vestibulum blandit luctus nisi a aliquet. Nulla fermentum arcu et nisl vulputate viverra. Proin viverra sit amet sapien faucibus maximus. Integer vel urna tempus, elementum erat nec, molestie mi. Vivamus ligula massa, lobortis ac enim sit amet, facilisis ultrices mauris. Mauris rutrum risus a sapien convallis, vitae lacinia est tempus. Donec elit leo, tincidunt id pellentesque vitae, tincidunt vel diam. Donec rhoncus scelerisque tellus sed tempor. Fusce a elit sed tellus venenatis vulputate. Aliquam sit amet lectus at lacus cursus pharetra. Aenean lacinia nisi velit. Nullam pretium odio vitae sapien efficitur auctor.
                            Maecenas suscipit urna id tellus efficitur pretium. Quisque eu ante arcu. Sed non leo et erat tempor pretium ut quis quam. Integer rhoncus dignissim nulla rhoncus dapibus. Sed viverra pretium congue. Donec tincidunt fermentum orci fringilla finibus. Aenean vitae arcu vel lacus tempus pulvinar ut vitae nunc. Suspendisse vel consectetur massa, non ullamcorper orci. Maecenas id dignissim justo. Sed ac euismod purus, id aliquet magna. Pellentesque porttitor erat commodo, imperdiet est ac, luctus orci. Sed eleifend augue non neque interdum ornare.
                            Aenean non porta enim, ut semper est. Aenean eleifend urna eu euismod efficitur. Morbi nec nibh non nisl mollis consectetur. Etiam et semper ex, quis congue magna. Nam venenatis risus ac tempus molestie. Ut ut ultrices ligula, sed iaculis ex. Vivamus viverra semper suscipit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis pretium rutrum pellentesque. Duis rhoncus mollis lacinia.
                            Mauris bibendum libero et dictum porta. Vivamus vulputate elit odio, tincidunt ultrices libero posuere ullamcorper. Curabitur orci est, malesuada at dignissim sed, aliquam eget ante. Praesent vitae est a augue molestie auctor ut eget enim. Sed iaculis aliquam diam ut venenatis. Nunc cursus, nunc ut facilisis vulputate, lectus tortor consequat nisl, viverra mattis neque sapien eget est. Nullam facilisis rhoncus quam, sed malesuada velit aliquam quis. Morbi et nibh eget tortor aliquet laoreet. Ut porta nulla at commodo facilisis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam dapibus purus sed ipsum egestas convallis. Sed et consequat quam. Praesent vel justo nec nisi imperdiet feugiat. Donec sapien ligula, euismod vel ultrices eget, condimentum eu risus.
                            Sed ultricies eleifend risus, quis aliquet velit sagittis eu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut interdum, sapien non dictum molestie, sem nunc porttitor ante, nec pellentesque dolor ex in massa. Donec iaculis in libero at pulvinar. Pellentesque porta libero vel orci malesuada volutpat. Sed dignissim eleifend odio, eget posuere libero suscipit id. Duis consequat ligula sit amet porttitor venenatis. Nam dapibus, libero quis posuere sodales, nulla nisi ultricies neque, et congue ligula quam sed nibh. Ut ligula mauris, pulvinar a sem sit amet, ullamcorper auctor urna. Quisque sollicitudin purus et ipsum tincidunt tempus viverra maximus est. Aliquam gravida, augue sed posuere accumsan, erat urna facilisis tortor, vitae accumsan metus purus vitae risus. Integer at lacinia orci, sed semper sapien. Donec in dui tristique, sagittis augue sit amet, faucibus augue.
                            Nunc feugiat dolor dapibus, facilisis sem vitae, viverra est. Nunc fringilla mi ut odio aliquet, quis condimentum diam interdum. Nulla eget lectus interdum, malesuada libero id, ultrices risus. Proin lacinia interdum pretium. Donec condimentum arcu sed augue commodo, a vestibulum magna commodo. Nullam neque eros, interdum et diam quis, lacinia tempus libero. Fusce aliquet pretium efficitur. Phasellus id egestas sem. Sed sagittis sapien nec condimentum vulputate. Donec posuere gravida metus. Nunc enim enim, malesuada non viverra sit amet, suscipit sed urna. Sed dapibus enim non scelerisque consequat. Suspendisse euismod ornare metus non laoreet. Vivamus vel dui at orci fringilla posuere convallis vitae lorem. Phasellus vel lacinia odio. Nulla convallis pretium mi non aliquet.</p>
                        <p className="font-bold text-xs mb-4">
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur nec fringilla dolor. Vestibulum blandit luctus nisi a aliquet. Nulla fermentum arcu et nisl vulputate viverra. Proin viverra sit amet sapien faucibus maximus. Integer vel urna tempus, elementum erat nec, molestie mi. Vivamus ligula massa, lobortis ac enim sit amet, facilisis ultrices mauris. Mauris rutrum risus a sapien convallis, vitae lacinia est tempus. Donec elit leo, tincidunt id pellentesque vitae, tincidunt vel diam. Donec rhoncus scelerisque tellus sed tempor. Fusce a elit sed tellus venenatis vulputate. Aliquam sit amet lectus at lacus cursus pharetra. Aenean lacinia nisi velit. Nullam pretium odio vitae sapien efficitur auctor.
                            Maecenas suscipit urna id tellus efficitur pretium. Quisque eu ante arcu. Sed non leo et erat tempor pretium ut quis quam. Integer rhoncus dignissim nulla rhoncus dapibus. Sed viverra pretium congue. Donec tincidunt fermentum orci fringilla finibus. Aenean vitae arcu vel lacus tempus pulvinar ut vitae nunc. Suspendisse vel consectetur massa, non ullamcorper orci. Maecenas id dignissim justo. Sed ac euismod purus, id aliquet magna. Pellentesque porttitor erat commodo, imperdiet est ac, luctus orci. Sed eleifend augue non neque interdum ornare.
                            Aenean non porta enim, ut semper est. Aenean eleifend urna eu euismod efficitur. Morbi nec nibh non nisl mollis consectetur. Etiam et semper ex, quis congue magna. Nam venenatis risus ac tempus molestie. Ut ut ultrices ligula, sed iaculis ex. Vivamus viverra semper suscipit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis pretium rutrum pellentesque. Duis rhoncus mollis lacinia.
                            Mauris bibendum libero et dictum porta. Vivamus vulputate elit odio, tincidunt ultrices libero posuere ullamcorper. Curabitur orci est, malesuada at dignissim sed, aliquam eget ante. Praesent vitae est a augue molestie auctor ut eget enim. Sed iaculis aliquam diam ut venenatis. Nunc cursus, nunc ut facilisis vulputate, lectus tortor consequat nisl, viverra mattis neque sapien eget est. Nullam facilisis rhoncus quam, sed malesuada velit aliquam quis. Morbi et nibh eget tortor aliquet laoreet. Ut porta nulla at commodo facilisis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam dapibus purus sed ipsum egestas convallis. Sed et consequat quam. Praesent vel justo nec nisi imperdiet feugiat. Donec sapien ligula, euismod vel ultrices eget, condimentum eu risus.
                            Sed ultricies eleifend risus, quis aliquet velit sagittis eu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut interdum, sapien non dictum molestie, sem nunc porttitor ante, nec pellentesque dolor ex in massa. Donec iaculis in libero at pulvinar. Pellentesque porta libero vel orci malesuada volutpat. Sed dignissim eleifend odio, eget posuere libero suscipit id. Duis consequat ligula sit amet porttitor venenatis. Nam dapibus, libero quis posuere sodales, nulla nisi ultricies neque, et congue ligula quam sed nibh. Ut ligula mauris, pulvinar a sem sit amet, ullamcorper auctor urna. Quisque sollicitudin purus et ipsum tincidunt tempus viverra maximus est. Aliquam gravida, augue sed posuere accumsan, erat urna facilisis tortor, vitae accumsan metus purus vitae risus. Integer at lacinia orci, sed semper sapien. Donec in dui tristique, sagittis augue sit amet, faucibus augue.
                            Nunc feugiat dolor dapibus, facilisis sem vitae, viverra est. Nunc fringilla mi ut odio aliquet, quis condimentum diam interdum. Nulla eget lectus interdum, malesuada libero id, ultrices risus. Proin lacinia interdum pretium. Donec condimentum arcu sed augue commodo, a vestibulum magna commodo. Nullam neque eros, interdum et diam quis, lacinia tempus libero. Fusce aliquet pretium efficitur. Phasellus id egestas sem. Sed sagittis sapien nec condimentum vulputate. Donec posuere gravida metus. Nunc enim enim, malesuada non viverra sit amet, suscipit sed urna. Sed dapibus enim non scelerisque consequat. Suspendisse euismod ornare metus non laoreet. Vivamus vel dui at orci fringilla posuere convallis vitae lorem. Phasellus vel lacinia odio. Nulla convallis pretium mi non aliquet.</p>
                        <p className="font-bold text-xs mb-4">
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur nec fringilla dolor. Vestibulum blandit luctus nisi a aliquet. Nulla fermentum arcu et nisl vulputate viverra. Proin viverra sit amet sapien faucibus maximus. Integer vel urna tempus, elementum erat nec, molestie mi. Vivamus ligula massa, lobortis ac enim sit amet, facilisis ultrices mauris. Mauris rutrum risus a sapien convallis, vitae lacinia est tempus. Donec elit leo, tincidunt id pellentesque vitae, tincidunt vel diam. Donec rhoncus scelerisque tellus sed tempor. Fusce a elit sed tellus venenatis vulputate. Aliquam sit amet lectus at lacus cursus pharetra. Aenean lacinia nisi velit. Nullam pretium odio vitae sapien efficitur auctor.
                            Maecenas suscipit urna id tellus efficitur pretium. Quisque eu ante arcu. Sed non leo et erat tempor pretium ut quis quam. Integer rhoncus dignissim nulla rhoncus dapibus. Sed viverra pretium congue. Donec tincidunt fermentum orci fringilla finibus. Aenean vitae arcu vel lacus tempus pulvinar ut vitae nunc. Suspendisse vel consectetur massa, non ullamcorper orci. Maecenas id dignissim justo. Sed ac euismod purus, id aliquet magna. Pellentesque porttitor erat commodo, imperdiet est ac, luctus orci. Sed eleifend augue non neque interdum ornare.
                            Aenean non porta enim, ut semper est. Aenean eleifend urna eu euismod efficitur. Morbi nec nibh non nisl mollis consectetur. Etiam et semper ex, quis congue magna. Nam venenatis risus ac tempus molestie. Ut ut ultrices ligula, sed iaculis ex. Vivamus viverra semper suscipit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis pretium rutrum pellentesque. Duis rhoncus mollis lacinia.
                            Mauris bibendum libero et dictum porta. Vivamus vulputate elit odio, tincidunt ultrices libero posuere ullamcorper. Curabitur orci est, malesuada at dignissim sed, aliquam eget ante. Praesent vitae est a augue molestie auctor ut eget enim. Sed iaculis aliquam diam ut venenatis. Nunc cursus, nunc ut facilisis vulputate, lectus tortor consequat nisl, viverra mattis neque sapien eget est. Nullam facilisis rhoncus quam, sed malesuada velit aliquam quis. Morbi et nibh eget tortor aliquet laoreet. Ut porta nulla at commodo facilisis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam dapibus purus sed ipsum egestas convallis. Sed et consequat quam. Praesent vel justo nec nisi imperdiet feugiat. Donec sapien ligula, euismod vel ultrices eget, condimentum eu risus.
                            Sed ultricies eleifend risus, quis aliquet velit sagittis eu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut interdum, sapien non dictum molestie, sem nunc porttitor ante, nec pellentesque dolor ex in massa. Donec iaculis in libero at pulvinar. Pellentesque porta libero vel orci malesuada volutpat. Sed dignissim eleifend odio, eget posuere libero suscipit id. Duis consequat ligula sit amet porttitor venenatis. Nam dapibus, libero quis posuere sodales, nulla nisi ultricies neque, et congue ligula quam sed nibh. Ut ligula mauris, pulvinar a sem sit amet, ullamcorper auctor urna. Quisque sollicitudin purus et ipsum tincidunt tempus viverra maximus est. Aliquam gravida, augue sed posuere accumsan, erat urna facilisis tortor, vitae accumsan metus purus vitae risus. Integer at lacinia orci, sed semper sapien. Donec in dui tristique, sagittis augue sit amet, faucibus augue.
                            Nunc feugiat dolor dapibus, facilisis sem vitae, viverra est. Nunc fringilla mi ut odio aliquet, quis condimentum diam interdum. Nulla eget lectus interdum, malesuada libero id, ultrices risus. Proin lacinia interdum pretium. Donec condimentum arcu sed augue commodo, a vestibulum magna commodo. Nullam neque eros, interdum et diam quis, lacinia tempus libero. Fusce aliquet pretium efficitur. Phasellus id egestas sem. Sed sagittis sapien nec condimentum vulputate. Donec posuere gravida metus. Nunc enim enim, malesuada non viverra sit amet, suscipit sed urna. Sed dapibus enim non scelerisque consequat. Suspendisse euismod ornare metus non laoreet. Vivamus vel dui at orci fringilla posuere convallis vitae lorem. Phasellus vel lacinia odio. Nulla convallis pretium mi non aliquet.</p>
                        <p className="font-bold text-xs mb-4">
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur nec fringilla dolor. Vestibulum blandit luctus nisi a aliquet. Nulla fermentum arcu et nisl vulputate viverra. Proin viverra sit amet sapien faucibus maximus. Integer vel urna tempus, elementum erat nec, molestie mi. Vivamus ligula massa, lobortis ac enim sit amet, facilisis ultrices mauris. Mauris rutrum risus a sapien convallis, vitae lacinia est tempus. Donec elit leo, tincidunt id pellentesque vitae, tincidunt vel diam. Donec rhoncus scelerisque tellus sed tempor. Fusce a elit sed tellus venenatis vulputate. Aliquam sit amet lectus at lacus cursus pharetra. Aenean lacinia nisi velit. Nullam pretium odio vitae sapien efficitur auctor.
                            Maecenas suscipit urna id tellus efficitur pretium. Quisque eu ante arcu. Sed non leo et erat tempor pretium ut quis quam. Integer rhoncus dignissim nulla rhoncus dapibus. Sed viverra pretium congue. Donec tincidunt fermentum orci fringilla finibus. Aenean vitae arcu vel lacus tempus pulvinar ut vitae nunc. Suspendisse vel consectetur massa, non ullamcorper orci. Maecenas id dignissim justo. Sed ac euismod purus, id aliquet magna. Pellentesque porttitor erat commodo, imperdiet est ac, luctus orci. Sed eleifend augue non neque interdum ornare.
                            Aenean non porta enim, ut semper est. Aenean eleifend urna eu euismod efficitur. Morbi nec nibh non nisl mollis consectetur. Etiam et semper ex, quis congue magna. Nam venenatis risus ac tempus molestie. Ut ut ultrices ligula, sed iaculis ex. Vivamus viverra semper suscipit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis pretium rutrum pellentesque. Duis rhoncus mollis lacinia.
                            Mauris bibendum libero et dictum porta. Vivamus vulputate elit odio, tincidunt ultrices libero posuere ullamcorper. Curabitur orci est, malesuada at dignissim sed, aliquam eget ante. Praesent vitae est a augue molestie auctor ut eget enim. Sed iaculis aliquam diam ut venenatis. Nunc cursus, nunc ut facilisis vulputate, lectus tortor consequat nisl, viverra mattis neque sapien eget est. Nullam facilisis rhoncus quam, sed malesuada velit aliquam quis. Morbi et nibh eget tortor aliquet laoreet. Ut porta nulla at commodo facilisis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam dapibus purus sed ipsum egestas convallis. Sed et consequat quam. Praesent vel justo nec nisi imperdiet feugiat. Donec sapien ligula, euismod vel ultrices eget, condimentum eu risus.
                            Sed ultricies eleifend risus, quis aliquet velit sagittis eu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut interdum, sapien non dictum molestie, sem nunc porttitor ante, nec pellentesque dolor ex in massa. Donec iaculis in libero at pulvinar. Pellentesque porta libero vel orci malesuada volutpat. Sed dignissim eleifend odio, eget posuere libero suscipit id. Duis consequat ligula sit amet porttitor venenatis. Nam dapibus, libero quis posuere sodales, nulla nisi ultricies neque, et congue ligula quam sed nibh. Ut ligula mauris, pulvinar a sem sit amet, ullamcorper auctor urna. Quisque sollicitudin purus et ipsum tincidunt tempus viverra maximus est. Aliquam gravida, augue sed posuere accumsan, erat urna facilisis tortor, vitae accumsan metus purus vitae risus. Integer at lacinia orci, sed semper sapien. Donec in dui tristique, sagittis augue sit amet, faucibus augue.
                            Nunc feugiat dolor dapibus, facilisis sem vitae, viverra est. Nunc fringilla mi ut odio aliquet, quis condimentum diam interdum. Nulla eget lectus interdum, malesuada libero id, ultrices risus. Proin lacinia interdum pretium. Donec condimentum arcu sed augue commodo, a vestibulum magna commodo. Nullam neque eros, interdum et diam quis, lacinia tempus libero. Fusce aliquet pretium efficitur. Phasellus id egestas sem. Sed sagittis sapien nec condimentum vulputate. Donec posuere gravida metus. Nunc enim enim, malesuada non viverra sit amet, suscipit sed urna. Sed dapibus enim non scelerisque consequat. Suspendisse euismod ornare metus non laoreet. Vivamus vel dui at orci fringilla posuere convallis vitae lorem. Phasellus vel lacinia odio. Nulla convallis pretium mi non aliquet.</p>
                    </div>
                </div>

                <div className="flex items-center gap-8 justify-center mb-10">
                    <Button className="flex py-1.5 px-5 items-center gap-2.5" variant='blue'>
                        <span>Sign</span>
                        <SignIcon />
                    </Button>

                    <Button className="flex py-1.5 px-5 items-center gap-2.5" variant='gold'>
                        <span>Download</span>
                        <DownloadIcon />
                    </Button>
                </div>
            </Paper>
            <div className="flex items-center justify-center mt-8">
                <Button className="flex py-1.5 px-2.5 items-center" variant='black'>
                    <span>Continue to Vaults</span>
                </Button>
            </div>
        </>
    );
}

export default ServiceAgreement;